spring:
  application:
    name: OnlinePetShop

  datasource:
    url: jdbc:mysql://localhost:3306/onlinepetshop
    username: root
    password: 1234567654321
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

security:
  jwt:
    secret-key: 7c560886eebbd6abbfce73507f9342151e68ae46c71528b97f63964a7deaaaf8
    expiration: 86400000

  sql:
    init:
      mode: always

server:
  port: 8088